-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 09:58:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `puffpet` DEFAULT CHARACTER SET utf8 ;
USE `puffpet` ;

-- -----------------------------------------------------
-- Table `puffpet`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` CHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`pet` (
  `idpet` INT NOT NULL AUTO_INCREMENT,
  `tipoanimal` VARCHAR(45) NOT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idpet`),
  INDEX `fk_pet_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_pet_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` CHAR(15) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `validade` VARCHAR(45) NOT NULL,
  `tipoproduto` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `idpet` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `idpet`),
  INDEX `fk_produto_pet1_idx` (`idpet` ASC),
  CONSTRAINT `fk_produto_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `mydb`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`cadastro_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`cadastro_produto` (
  `idproduto` INT NOT NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `idcliente`),
  INDEX `fk_produto_has_cliente_cliente1_idx` (`idcliente` ASC),
  INDEX `fk_produto_has_cliente_produto_idx` (`idproduto` ASC),
  CONSTRAINT `fk_produto_has_cliente_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_cliente_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaosocial` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `cnpj` BIGINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puffpet`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puffpet`.`login` (
  `idfuncionario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idfornecedor` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  INDEX `fk_login_funcionario1_idx` (`idfuncionario` ASC),
  INDEX `fk_login_cliente1_idx` (`idcliente` ASC),
  INDEX `fk_login_fornecedor1_idx` (`idfornecedor` ASC),
  CONSTRAINT `fk_login_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_fornecedor1`
    FOREIGN KEY (`idfornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
